<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;</TargetFrameworks>
    <RootNamespace>OsuParsers</RootNamespace>
    <Authors>mrflashstudio</Authors>
    <Company />
    <Description>Forked for easier modification of Mania beatmaps</Description>
    <Copyright></Copyright>
    <RepositoryUrl>https://github.com/krrcream/OsuParsers</RepositoryUrl>
    <PackageProjectUrl>https://github.com/krrcream/OsuParsers</PackageProjectUrl>
    <PackageId>krrcream.OsuParsers</PackageId>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IsPackable>true</IsPackable>
    <Version>1.0.0.0</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />
  </ItemGroup>
</Project>