<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;</TargetFrameworks>
    <RootNamespace>OsuParsers</RootNamespace>
    <Authors>mrflashstudio</Authors>
    <Company />
    <Version>1.8.2.0</Version>
    <Description>Forked for easier modification of Mania beatmaps</Description>
    <Copyright></Copyright>
    <RepositoryUrl>https://github.com/krrcream/OsuParsers</RepositoryUrl>
    <PackageProjectUrl>https://github.com/krrcream/OsuParsers</PackageProjectUrl>
    <AssemblyVersion>1.8.2.0</AssemblyVersion>
    <FileVersion>1.8.2.0</FileVersion>
    <PackageVersion>1.8.2.0</PackageVersion>
    <PackageId>krrcream.OsuParsers</PackageId>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />
  </ItemGroup>
</Project>